// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBL3.Models;

#nullable disable

namespace PBL3.Migrations
{
    [DbContext(typeof(TrafficDbContext))]
    [Migration("20260130061812_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrafficApp.Complaint", b =>
                {
                    b.Property<string>("ComplaintId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ViolationId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ComplaintId");

                    b.HasIndex("UserId");

                    b.HasIndex("ViolationId");

                    b.ToTable("Complaint");
                });

            modelBuilder.Entity("TrafficApp.ComplaintHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplaintId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HandlerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("HandlerId");

                    b.ToTable("ComplaintHistory");
                });

            modelBuilder.Entity("TrafficApp.DrivingLicense", b =>
                {
                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LicenseNumber");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DrivingLicense");
                });

            modelBuilder.Entity("TrafficApp.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("TrafficApp.PaymentHistory", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViolationId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ViolationId");

                    b.ToTable("PaymentHistory");
                });

            modelBuilder.Entity("TrafficApp.RegulationTrafficLaw", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegulationTrafficLaw");
                });

            modelBuilder.Entity("TrafficApp.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserRole").HasValue("User");
                });

            modelBuilder.Entity("TrafficApp.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TrafficApp.Violation", b =>
                {
                    b.Property<string>("ViolationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ViolationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViolationTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ViolationId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ViolationTypeId");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("TrafficApp.ViolationType", b =>
                {
                    b.Property<string>("ViolationTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("FineMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FineMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegulationId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ViolationTypeId");

                    b.HasIndex("RegulationId");

                    b.ToTable("ViolationTypes");
                });

            modelBuilder.Entity("TrafficApp.Admin", b =>
                {
                    b.HasBaseType("TrafficApp.User");

                    b.HasDiscriminator().HasValue("ADMIN");
                });

            modelBuilder.Entity("TrafficApp.Customer", b =>
                {
                    b.HasBaseType("TrafficApp.User");

                    b.HasDiscriminator().HasValue("CUSTOMER");
                });

            modelBuilder.Entity("TrafficApp.Officer", b =>
                {
                    b.HasBaseType("TrafficApp.User");

                    b.Property<string>("BadgeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OFFICER");
                });

            modelBuilder.Entity("TrafficApp.Complaint", b =>
                {
                    b.HasOne("TrafficApp.User", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId");

                    b.HasOne("TrafficApp.Violation", "Violation")
                        .WithMany("Complaints")
                        .HasForeignKey("ViolationId");

                    b.Navigation("User");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("TrafficApp.ComplaintHistory", b =>
                {
                    b.HasOne("TrafficApp.Complaint", "Complaint")
                        .WithMany("Histories")
                        .HasForeignKey("ComplaintId");

                    b.HasOne("TrafficApp.User", "Handler")
                        .WithMany()
                        .HasForeignKey("HandlerId");

                    b.Navigation("Complaint");

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("TrafficApp.DrivingLicense", b =>
                {
                    b.HasOne("TrafficApp.User", "User")
                        .WithMany("DrivingLicenses")
                        .HasForeignKey("UserId");

                    b.HasOne("TrafficApp.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TrafficApp.Notification", b =>
                {
                    b.HasOne("TrafficApp.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficApp.PaymentHistory", b =>
                {
                    b.HasOne("TrafficApp.Violation", "Violation")
                        .WithMany("Payments")
                        .HasForeignKey("ViolationId");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("TrafficApp.Vehicle", b =>
                {
                    b.HasOne("TrafficApp.User", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TrafficApp.Violation", b =>
                {
                    b.HasOne("TrafficApp.Officer", "Officer")
                        .WithMany("Violations")
                        .HasForeignKey("OfficerId");

                    b.HasOne("TrafficApp.Vehicle", "Vehicle")
                        .WithMany("Violations")
                        .HasForeignKey("VehicleId");

                    b.HasOne("TrafficApp.ViolationType", "ViolationType")
                        .WithMany("Violations")
                        .HasForeignKey("ViolationTypeId");

                    b.Navigation("Officer");

                    b.Navigation("Vehicle");

                    b.Navigation("ViolationType");
                });

            modelBuilder.Entity("TrafficApp.ViolationType", b =>
                {
                    b.HasOne("TrafficApp.RegulationTrafficLaw", "Regulation")
                        .WithMany("ViolationTypes")
                        .HasForeignKey("RegulationId");

                    b.Navigation("Regulation");
                });

            modelBuilder.Entity("TrafficApp.Complaint", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("TrafficApp.RegulationTrafficLaw", b =>
                {
                    b.Navigation("ViolationTypes");
                });

            modelBuilder.Entity("TrafficApp.User", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("DrivingLicenses");

                    b.Navigation("Notifications");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TrafficApp.Vehicle", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("TrafficApp.Violation", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TrafficApp.ViolationType", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("TrafficApp.Officer", b =>
                {
                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
